
import { config } from 'dotenv';
config();

import '@/ai/flows/generate-report-summary.ts';
import '@/ai/flows/generate-report-summary-types.ts';
import '@/ai/flows/generate-lesson-plan.ts';
import '@/ai/flows/generate-lesson-plan-types.ts';
import '@/ai/flows/mwalimu-ai-flow.ts';
import '@/ai/flows/mwalimu-ai-types.ts';
import '@/ai/flows/generate-scheme-of-work.ts';
import '@/ai/flows/generate-scheme-of-work-types.ts';
import '@/ai/flows/generate-rubric.ts';
import '@/ai/flows/generate-rubric-types.ts';
import '@/ai/flows/classroom-compass-flow.ts';
import '@/ai/flows/classroom-compass-types.ts';
import '@/ai/flows/generate-worksheet.ts';
import '@/ai/flows/generate-worksheet-types.ts';
import '@/ai/flows/differentiate-worksheet.ts';
import '@/ai/flows/differentiate-worksheet-types.ts';
import '@/ai/flows/improve-lesson-plan.ts';
import '@/ai/flows/improve-lesson-plan-types.ts';
import '@/ai/flows/generate-dashboard-summary.ts';
import '@/ai/flows/generate-dashboard-summary-types.ts';
import '@/ai/flows/school-head-consultant.ts';
import '@/ai/flows/school-head-consultant-types.ts';
import '@/ai/flows/generate-county-summary.ts';
import '@/ai/flows/generate-county-summary-types.ts';
import '@/ai/flows/ingest-curriculum.ts';
import '@/ai/flows/ingest-curriculum-types.ts';
import '@/ai/flows/generate-family-email.ts';
import '@/ai/flows/generate-family-email-types.ts';
import '@/ai/flows/summarize-student-interaction.ts';
import '@/ai/flows/generic-teacher-tool.ts';
