
/**
 * @fileOverview Curriculum data for Pre-Primary 1 Language Activities.
 * 
 * This file contains the structured curriculum content that will be used
 * by the AI to generate lesson plans, schemes of work, and other resources.
 * This data is extracted from the KICD PP1 Language Activities curriculum design document.
 */

export const pp1LanguageActivitiesCurriculum = {
  grade: "PP1",
  subject: "Language Activities",
  strands: [
    {
      title: "1.0 GREETINGS AND FAREWELL",
      sub_strands: [
        {
          title: "1.1 Greetings and Farewell",
          learning_outcomes: [
            "mention why we greet each other in our day-to-day life",
            "use greetings in social interactions",
            "use farewell words and gestures in social interactions",
            "appreciate the importance of greetings and bidding farewell in daily interactions",
          ],
          suggested_activities: [
            "say why people greet each other",
            "say people who have greeted them and those they have greeted",
            "collaboratively imitate greetings",
            "imitate bidding of farewell",
            "watch a video clip or listen to an audio recording on people greeting and bidding farewell",
            "discuss pictures on people greeting one another and bidding farewell",
            "role play people initiating and responding to greetings",
            "role play people bidding farewell using words and gestures",
            "sing songs related to greetings and bidding of farewell",
          ],
          key_inquiry_questions: ["Why do we greet people?"],
        },
        {
          title: "1.2 Time related greetings and farewell",
          learning_outcomes: [
            "state words we use to greet at different times of the day",
            "use time related greetings correctly",
            "express farewell words and gestures in relation to time",
            "acknowledge use of greetings and bidding of farewell in social interactions",
          ],
          suggested_activities: [
            "talk about different greetings used at different times of the day (good morning, good afternoon, good evening)",
            "greet and bid farewell to each other using the right words",
            "relate words used in bidding farewell to different times of the day (good bye, good night, see you later)",
            "role play greeting and bidding farewell to one another relating to different times of the day",
            "sing songs on time related greetings using words and gestures",
            "sing songs on bidding farewell at different times of the day using words and gestures",
          ],
          key_inquiry_questions: ["Why do we bid people farewell at different times?"],
        },
        {
          title: "2.1 Reading readiness",
          learning_outcomes: [
            "describe how we move eyes when reading",
            "demonstrate top-down orientation in reading",
            "turn pages from right to left when opening a book",
            "embrace caring for books in preparation for reading",
          ],
          suggested_activities: [
            "explain in pairs or groups how we move eyes when reading",
            "read pictures arranged from the top to the bottom of a page or chart",
            "view a video clip or observe pictures of sequenced activities arranged from left to right in the correct order",
            "read given series of pictures arranged from left to right as they narrate the happenings",
            "turn pages of a picture book from right to left",
            "play a game on turning picture book pages where they tap in advance all pages with a picture responsibly to avoid tearing",
          ],
          key_inquiry_questions: ["How can we take care of our books?"],
        },
        {
          title: "3.1 Print awareness",
          learning_outcomes: [
            "identify given pictures of familiar things within the environment",
            "scribble freely on books in preparation for writing",
            "Have fun while scribbling on books and other surfaces in preparation for writing",
          ],
          suggested_activities: [
            "recognize pictures of familiar things within their environment (on charts, books, digital devices)",
            "talk about the pictures",
            "hold pencils, pens, sticks crayons or coloring pictures pencils correctly and scribble freely on surfaces",
            "display their scribbled work for self and peer assessment",
            "freely colour pictures of familiar things in their environment",
            "model pictures of familiar things in the environment",
            "clear the working space",
            "wash hands with clean water the modelling experience",
            "sing songs while colouring pictures in the environment for motivation",
          ],
          key_inquiry_questions: ["How can we make pictures?"],
        },
      ],
    },
    {
      title: "2.0 MYSELF",
      sub_strands: [
        {
          title: "1.2 Self awareness",
          learning_outcomes: [
            "identify self by name",
            "distinguish self as girl or boy",
            "recite a poem mentioning their age",
            "acknowledge the importance of personal identity",
          ],
          suggested_activities: [
            "take turns to say own name in full",
            "discuss why children should have names",
            "share what they know about being a girl or being a boy",
            "participate in poems on self-awareness saying their name, gender and age (teacher-made, pre-recorded)",
            "play games on self-awareness",
          ],
          key_inquiry_questions: ["Why is it important to know yourself?"],
        },
        {
          title: "1.1 Listening for enjoyment",
          learning_outcomes: [
            "name different songs children sing",
            "sing different children’s songs",
            "demonstrate ways of dancing to children’s songs using different parts of the body",
            "value listening to music for enjoyment",
          ],
          suggested_activities: [
            "talk about the songs they know",
            "sing children songs while others listen",
            "imitate songs with actions and movements as a group, in pairs and later individually",
            "listen to audio or videos records of children’s music",
            "show various body movements using (fingers, head, waist, feet, shoulders) in response to music/dancing",
            "respond to music in various ways by tapping, nodding or shaking",
          ],
          key_inquiry_questions: [
            "How do people respond to songs?",
            "Why do people sing?",
          ],
        },
        {
            title: "2.1 Book handling",
            learning_outcomes: [
                "state ways of taking care of books",
                "organise books in a bag",
                "arrange books for safe keeping",
                "turn over pages of a book from right to left",
                "advocate for appropriate handling of books for sustainability",
            ],
            suggested_activities: [
                "share experiences on how books should be taken care of to avoid destruction",
                "observe teachers’ demonstration on how to arrange books in bags, on shelves, cupboards and tables",
                "work together to arrange books appropriately in bags, on shelves, cupboards or tables",
                "display arranged books for others to see and assess",
                "take turns in checking the handling of books by peers",
                "turn over pages from right to left",
                "turn each page gently",
            ],
            key_inquiry_questions: ["How do you take care of books?"],
        },
        {
            title: "2.2 Reading posture",
            learning_outcomes: [
                "identify correct reading posture in given pictures",
                "use an appropriate posture when reading",
                "acknowledge the importance of correct posture when reading",
            ],
            suggested_activities: [
                "view pictures of correct and incorrect reading postures video clips, charts or books",
                "distinguish correct reading posture from incorrect reading posture based on the video clip, or charts and books",
                "observe correct reading posture demonstrated by the teacher",
                "practice correct reading posture",
                "sing songs on correct reading posture as they practice the correct posture",
                "observe peers and assess each other on correct reading posture",
            ],
            key_inquiry_questions: ["Why do we need to sit upright as we read?"],
        },
        {
            title: "3.1 Writing posture",
            learning_outcomes: [
                "identify appropriate sitting posture when scribbling, drawing and writing",
                "sit appropriately when scribbling, colouring and writing",
                "consult on appropriate sitting posture when involved in pre-writing and writing experiences",
            ],
            suggested_activities: [
                "select the correct sitting posture from a variety of pictures",
                "observe demonstration of appropriate sitting posture when writing either from the teacher or a video clip",
                "practice the correct writing posture following demonstration from the teacher or a video clip",
                "model objects using either clay, dough or plasticine while using correct sitting posture in preparation for writing",
                "recite a simple poem on appropriate sitting posture while using actions",
            ],
            key_inquiry_questions: ["How do we sit appropriately when writing?", "Why sit appropriately when writing?"],
        },
        {
            title: "3.2 Pre writing skills",
            learning_outcomes: [
                "identify different materials used in writing and colouring",
                "demonstrate the ability to scribble from up to bottom of the page",
                "demonstrate the ability to scribble from left to right",
                "colour pictures within borders",
                "take pleasure in scribbling and colouring within borders of shapes",
            ],
            suggested_activities: [
                "name different writing materials and tools (books, pencils, colour pencils, sticks)",
                "scribble on books from up to bottom of the page",
                "scribble from the left to the right side of the pages",
                "hold a book appropriately when colouring",
                "colour pictures within borders appropriately and show peers",
                "sit in the right posture while scribbling as earlier demonstrated",
            ],
            key_inquiry_questions: ["Which materials do you require when writing?"],
        }
      ],
    },
    {
        title: "3.0 MY FAMILY",
        sub_strands: [
            {
                title: "1.1 Active listening",
                learning_outcomes: [
                    "name family members using their appropriate titles as they refer to them",
                    "tell short stories about family members",
                    "respond to simple instructions",
                    "participate with pleasure in reciting poems about family members",
                ],
                suggested_activities: [
                    "say members of the family",
                    "tell their relationship with the members of the family. (father, mother, brother, sister)",
                    "to one another tell stories about family members",
                    "tell news about family members",
                    "sing songs about family members",
                    "answer questions on family members",
                    "role play family members",
                    "respond appropriately to instructions on family",
                    "recite poems on family members",
                ],
                key_inquiry_questions: ["What do you like about your family?"],
            },
            {
                title: "1.2 Self-expression",
                learning_outcomes: [
                    "identify the appropriate titles of family members",
                    "tell stories in details about family members",
                    "mention work done by family members",
                    "recommend family members for what they do",
                ],
                suggested_activities: [
                    "tell news about family members",
                    "tell who are the members of the family and the ones not",
                    "tell stories about members of the family, (sister, brother, mother, self and father), their names, what they do, where they live, what they like…",
                    "name work done by different members of the family",
                    "sing songs about family members",
                    "role play work done by family members",
                ],
                key_inquiry_questions: ["What work is done by different members of the family?"],
            },
            {
                title: "1.3 Polite language",
                learning_outcomes: [
                    "identify words that depict polite language in daily interactions",
                    "use polite language in daily interactions",
                    "Appreciate the use of polite language in day-to day interactions",
                ],
                suggested_activities: [
                    "name words used to request, apologise and appreciate",
                    "tell why we should use polite language in day-to-day interactions",
                    "engage in dialogue using polite language in class (please, thank you, may I? kindly,)",
                    "use appropriate polite language while",
                    "role playing work done by family members",
                    "watch a video clip or listen to a recording on use of polite language",
                    "talk about pictures showing gestures on use of polite language",
                ],
                key_inquiry_questions: ["Why do we use polite language?", "When do we use polite language?"],
            },
            {
                title: "2.1 Print awareness",
                learning_outcomes: [
                    "name pictures of clothes worn by family members",
                    "differentiate pictures of food eaten by family members",
                    "Actively participate in identifying pictures related to family",
                ],
                suggested_activities: [
                    "read aloud pictures on books, charts and boards on clothes worn by family members",
                    "talk about pictures showing clothes worn by boys and those worn by girls",
                    "role play washing clothes worn by family members",
                    "watch a video clip on different types of foods (read pictures on different types of food)",
                    "identify the types of food watched on the video or read on the pictures",
                    "talk about different foods eaten at home",
                    "play a look and say game using pictures of foods eaten by family members",
                    "fix puzzles using broken pictures of clothes worn by family members (vest, shirt, dress)",
                    "bring picture cut outs on family members, clothes or food from old books, gazettes or magazines",
                    "sing songs related to family",
                ],
                key_inquiry_questions: ["Why do family members wear different types of clothes?"],
            },
            {
                title: "2.2 Phonic awareness",
                learning_outcomes: [
                    "identify the first five letter sounds of the alphabet (a, b, c, d, e)",
                    "match the first five letter sounds of the alphabet with corresponding objects whose name begin with the sound for mastery (a, b, c, d, e)",
                    "choose to chant rhymes on the letter sounds",
                ],
                suggested_activities: [
                    "listen to the first five letter sounds of the alphabet (from the teacher or an audio recording) then repeat",
                    "read out the first five letter sounds of the alphabet in groups and in pairs then individually",
                    "recognize the letter sounds from charts, books, cards or any other written material within the class",
                    "match the letter sounds with corresponding objects whose name begin with the letter sound (a for apple, b for boy, c for cat)",
                    "play letter sound recognition game like a fishing game (picking randomly learnt letter sounds from a box or basket and read it out)",
                    "chant rhymes related to the learnt letter sounds for mastery",
                ],
                key_inquiry_questions: ["What pictures do you enjoy reading?", "Which letters sound the same?"],
            },
            {
                title: "3.1 Eye-hand Co-ordination",
                learning_outcomes: [
                    "describe what to look at when writing",
                    "coordinate the eye and hand when writing",
                    "open pages of a book from left to right to continue writing",
                    "make attempts of holding a writing tool and write from left to the right side of a book",
                ],
                suggested_activities: [
                    "listen to the teacher’s explanation about looking keenly while handling the writing material",
                    "observe the teacher’s demonstration of how to have the eyes focused on the writing material",
                    "talk about what to do and what to look at when writing",
                    "practice focusing their eyes on the writing material as they write individually and collaboratively",
                    "turn pages from right to left gently to continue writing without skipping pages",
                    "fix puzzles collaboratively using cut pieces of learnt letter sounds to make them whole",
                ],
                key_inquiry_questions: ["Why should we look at our books when writing?", "How do we hold our books and pens/pencils when writing?"],
            },
            {
                title: "3.2 Writing readiness",
                learning_outcomes: [
                    "identify materials that are required for writing",
                    "hold a writing tool in readiness for writing",
                    "join dots correctly to complete writing letter sounds a, b, c, d, e",
                    "practice holding a writing tool and putting marks on surfaces",
                    "embrace the use of writing materials to improve writing",
                ],
                suggested_activities: [
                    "mention materials like pencils, colour pencils and books",
                    "hold a pencil or color pencil correctly between the index finger and the thumb while resting on the middle finger",
                    "write the learnt letter sounds in the air while facing same direction (a, b, c, d, e)",
                    "place a book correctly ready for writing",
                    "join dots of letter sounds from left to right on their books filling each page from top to bottom",
                    "model letter sounds in groups for mastery using clay, plasticine or dough",
                    "sing songs related to letter sounds with peers as they join the dots",
                ],
                key_inquiry_questions: ["How do we hold our pencils or pens when writing?", "Where do we write on?"],
            }
        ],
    },
    {
        title: "4.0 MY HOME",
        sub_strands: [
            {
                title: "1.1 Naming",
                learning_outcomes: [
                    "name things found at home",
                    "name people found at home",
                    "construct simple sentences using vocabulary related to things found at home",
                    "use vocabulary related to people found at home",
                    "enjoy activities that involve naming of things and people found at home",
                ],
                suggested_activities: [
                    "assign correct names to objects and items found at home",
                    "mention names of members of the family and other people found in the home",
                    "engage in simple conversations using sentences and talking about objects and items found at home in relation to colour, shape, size and use",
                    "talk about members of the family and other people in relation to their different roles",
                    "listen to an audio clip with a story on things found at home",
                    "answer oral questions from the audio clip on things found at home",
                    "collaboratively engages in vocabulary games about things and people found at home",
                    "view and discuss video clip on things and people found at home",
                    "discuss use of different objects found at home",
                    "recite poems and rhymes about things and people found at home",
                ],
                key_inquiry_questions: ["How do people use different things found in the home?"],
            },
            {
                title: "1.2 Passing information",
                learning_outcomes: [
                    "identify similarities of things found at home",
                    "discuss the differences in things found at home",
                    "talk about the differences in people found at home",
                    "use relevant vocabulary to pass verbal information about the environment in relation to things found at home",
                    "show involvement by contributing in the passing of verbal messages about the home environment",
                ],
                suggested_activities: [
                    "mention similarities in things found at home",
                    "mention differences in things found at home",
                    "name different buildings found at home like cowshed, latrine/toilet, houses, kitchen",
                    "read aloud pictures of things found at home such as furniture (tables, stools, coaches), utensils (spoons, cups, kettles, knives, pot…), animals and people",
                    "tell the differences in people found at home",
                    "in groups mention things found within the home environment using relevant vocabulary",
                    "collaboratively talk about things found at home that can be harmful and how they can avoid them",
                    "talk about differences in animals found at home",
                    "sing songs about things found at home",
                ],
                key_inquiry_questions: ["Why do we have different things and people at home?", "How can some of the items and objects found at home injure us?"],
            },
            {
                title: "2.1 Visual discrimination",
                learning_outcomes: [
                    "recognise pictures of things found at home",
                    "points out similarities in pictures of objects found at home",
                    "points out differences in pictures of objects found at home",
                    "enjoy pointing out differences in observed things in the environment",
                ],
                suggested_activities: [
                    "read pictures of things found at home such as people, animals, houses, farm tools, furniture, utensils, digital devices, clothes and plants either from a video clip, books, cards, charts or board",
                    "identify similarities in the pictures on their use, where they are found, color, size",
                    "identify the differences in digital pictures of objects found at home and their uses",
                    "collaboratively looks at the things found in the class and relate them to some things found at home for example, tables, desks and furniture at home, buildings, plants, toilets…",
                    "talk about things in school that are not found at home, as well as things at home that are not in school",
                    "talk about how to care of the things found at home",
                    "sing songs related to things found at home",
                ],
                key_inquiry_questions: ["How do we use different items and objects found at home?", "How do we take care of the things found at home?"],
            },
            {
                title: "2.2 Phonic awareness",
                learning_outcomes: [
                    "read letter sounds of the alphabet (f g h i j)",
                    "articulate correctly all the learnt letter sounds (a-j)",
                    "match learnt letter sounds with corresponding objects whose names begin with the sound",
                    "participate with pleasure in activities related to reading",
                ],
                suggested_activities: [
                    "name the second set of 5 letter sounds in the alphabet",
                    "pick letter cards randomly and read out the sounds",
                    "match letter sounds with corresponding object names whose names begin with the learnt sound",
                    "chant rhymes on letter sounds in groups, in pairs and individuals",
                    "play letter sound fishing game by picking a letter sound from a box, bag or basket, reads it out and displays as other learners confirm if read out correctly",
                    "sing songs related to letter sounds",
                ],
                key_inquiry_questions: ["Why are there different sounds in the environment?"],
            },
            {
                title: "3.1 Writing readiness",
                learning_outcomes: [
                    "name tools used for writing",
                    "show how to hold writing tool correctly",
                    "Participate in prewriting letter sounds",
                    "enjoy participating in pre-writing activities in",
                ],
                suggested_activities: [
                    "list different tools used for writing such as pencil, colour pencils, pens",
                    "name different tools that can be used for writing",
                    "demonstrate how to hold a writing tool correctly (index finger and the thumb supported by the middle finger)",
                    "write letter sounds a, b, c, d, e in the air and on the ground",
                    "colour the above letter sounds",
                    "join dots to complete letter sounds a, b, c, d, e",
                    "chant rhymes on letter sounds a, b, c, d, e in groups, in pairs and as individuals",
                    "model letter sounds a, b, c, d, e using clay, plasticine or dough",
                    "wash hands after modelling",
                    "display own work for others to see and wash their hands with soap and water",
                ],
                key_inquiry_questions: ["Why do we write?"],
            },
            {
                title: "3.2 Writing letter sounds",
                learning_outcomes: [
                    "identify the first five letter sounds (a, b, c, d, e)",
                    "write the first five letters of the alphabet that match the sounds learned",
                    "write the second set of five letter sounds (f, g, h, i, j)",
                    "enjoy participating in writing activities",
                ],
                suggested_activities: [
                    "recognize the first five letter sounds (a, b, c, d, e)",
                    "write the first 5 letter sounds in books",
                    "read letter sounds f,g,h,i,j on books, charts, board, from a digital device or cards",
                    "observe teacher write letter sounds f,g,h,i,j one by one while facing same direction",
                    "write in the air letter sounds f,g,h,i,j",
                    "Join dots for letter sounds f,g,h i,j",
                    "in pairs or small groups, learner to trace and shade outlines of letter sound f,g,h,i j",
                    "colour and paint letter sounds a,b,c,d,e while singing related rhymes",
                    "model letter sounds f,g,h,i,j in groups and in pairs",
                    "display their modelled painted and coloured work",
                ],
                key_inquiry_questions: ["How can we write on different surfaces?"],
            }
        ],
    },
    {
        title: "5.0 MY NEIGHBOURHOOD",
        sub_strands: [
            {
                title: "1.1 Environmental awareness",
                learning_outcomes: [
                    "name things found in the neighbourhood",
                    "construct simple sentences about things in the neighbourhood",
                    "enjoy observing the neighbouring environment for familiarisation",
                ],
                suggested_activities: [
                    "engage in naming different things in the neighboring environment like pets, roads, cars, animals, play fields, people, and houses",
                    "talk about use of those things in the neighbourhood",
                    "listen to peers sentences about uses of things in the environment",
                    "view a video clip that shows common things found in different environments",
                    "talk about similarities of things in the neighbourhood",
                    "talk about differences of things in the neighbourhood",
                    "sing songs about things found in the neighbourhood",
                    "recite poems about things found in the environment and their care",
                ],
                key_inquiry_questions: ["How do we use different things in our environment?"],
            },
            {
                title: "1.2 Auditory discrimination",
                learning_outcomes: [
                    "recognize various sounds in the environment",
                    "respond appropriately to sounds that represent safety in the environment",
                    "respond appropriately to sounds that represent danger in the environment",
                    "advocate for correct responses to sounds in the environment",
                ],
                suggested_activities: [
                    "name things that make different sounds in the environment in and outside school such as bells, animals, alarms, vehicles, crying babies and phones",
                    "identify sounds in the environment that communicate safety like claps, cheers, laughter",
                    "identify sounds in the environment that communicate danger like sirens of ambulance and fire extinguisher, screams and barking dogs",
                    "role play both safe and dangerous situations that are represented by certain sounds in the environment",
                    "go for a nature walk within school compound and identify sounds heard",
                    "identify different sounds in a sound recognition game, blind folded",
                ],
                key_inquiry_questions: ["How do you respond to different sounds in the environment?"],
            },
            {
                title: "1.3 Audience awareness",
                learning_outcomes: [
                    "mention ways to ensure that one is audible",
                    "speak clearly and loudly when talking to others in and out of class",
                    "exhibit audience awareness while speaking to a group of people",
                ],
                suggested_activities: [
                    "interact with each other to discuss how to be audible when speaking",
                    "listen to a recording or the teacher reading a short story clearly and audibly",
                    "listen to news or presentation from radio",
                    "imitate brief statements from the recording, teacher and radio",
                    "talk loudly and clearly about things found in the neighbourhood while projecting voice as others listen",
                    "to present songs, poems and rhymes in class, during parade and get feedback from friends and teacher on clarity and audibility",
                ],
                key_inquiry_questions: ["Why do people talk sometimes loudly and other times softly?"],
            },
            {
                title: "2.1 Visual memory",
                learning_outcomes: [
                    "recognise pictures of things found in the neighbourhood",
                    "demonstrate awareness of use of objects in the neighbourhood with pictures presented",
                    "initiate reading of pictures when interacting with print materials",
                ],
                suggested_activities: [
                    "respond to questions about pictures of things found in the neighbourhood either from charts, a digital device, books or board",
                    "take turns to discuss with peers the use of pictures of things found in the neighbourhood",
                    "collaboratively role play use of things found in the neighbourhood",
                    "look at pictures on a page within given time, put the book away and recall the pictures seen earlier",
                    "talk about use of things in the neighbourhood",
                    "match pictures in books, cards or charts with people and items they use e g a police man and a gun, a farmer and a jembe, a nurse and a syringe a cook and a sufuria…)",
                    "view items in a learning corner in the class-room and answer questions to recall what they saw",
                    "recite poems on things found in the neighbourhood",
                    "sing songs about things that they have seen in the neighbourhood",
                ],
                key_inquiry_questions: ["What did you observe on the way as you were coming to school?"],
            },
            {
                title: "2.2 Phonic awareness",
                learning_outcomes: [
                    "read sounds representing letters of the alphabet in a sequence",
                    "match learnt sounds correctly with objects whose name begin with similar sound for mastery",
                    "chant rhymes on learnt sounds",
                    "participate in sound recognition activities",
                ],
                suggested_activities: [
                    "identify the sounds in a sequence (k, l, m, n, o, p, q, r, s, t)",
                    "identify the learnt sounds from charts, board, books, cards and labels in pairs to enhance sound recognition",
                    "select objects and pictures whose names begin with the learnt sound for memorization (k for kite, l for ladder...)",
                    "sing songs, recite poems and chant rhymes related to sounds corresponding to letters displayed letters",
                    "play letter recognition games like fishing letter games and letter sorting to reinforce understanding of sounds",
                    "compete in sound recognition games and show fairness in winning and acceptance in loosing",
                ],
                key_inquiry_questions: ["Which things have sound ‘b’ in their name?"],
            },
            {
                title: "3.1 Pattern writing",
                learning_outcomes: [
                    "identify patterns written using letters of the alphabet",
                    "use writing tools appropriately to make pattern",
                    "participate in activities related to pattern writing",
                ],
                suggested_activities: [
                    "recall learnt letter sounds using a chart",
                    "demonstrate the meaning of a pattern as repeated arrangement using physical objects in the class such as sticks, letter cards, books",
                    "write learnt letter sounds in the air facing same direction as the teacher",
                    "observe the teacher writing a letter sound pattern",
                    "write in the air the demonstrated letter sound pattern",
                    "complete writing a letter sound pattern, in pairs",
                    "complete writing a letter sound pattern individually",
                    "display completed letter sound patterns to others in class for peer assessment",
                ],
                key_inquiry_questions: ["Why do we sometimes write something repeatedly?"],
            },
            {
                title: "3.2 Phonic awareness",
                learning_outcomes: [
                    "write letters of the alphabet correctly in and out of class (r, s, t, u, v, w, x, y, z)",
                    "match letter sounds with corresponding objects whose name begin with same sound for mastery",
                    "take pleasure in using basic tools for writing in class",
                ],
                suggested_activities: [
                    "write learnt letters of the alphabet in the air (r, s, t, u, v, w, x, y, z)",
                    "join dots to complete letters of the alphabet",
                    "trace and copy letters of the alphabet",
                    "model letters of the alphabet using clay, dough or plasticine",
                    "practice writing letters of the alphabet using ICT letter writing games",
                    "write letters of the alphabet in writing books, chalkboard, on the ground or other materials",
                    "make patterns using letters of the alphabet",
                    "Models letters of the alphabet and washes hands after",
                    "in pairs and groups learners make patterns using letters of the alphabet",
                    "display work done by groups for peer assessment and feedback",
                ],
                key_inquiry_questions: ["What do we need to use to write letters of the alphabet?", "Where can we read letters of the alphabet?"],
            }
        ],
    },
    {
        title: "6.0 MY SCHOOL",
        sub_strands: [
            {
                title: "1.1 Auditory memory",
                learning_outcomes: [
                    "recall a variety of sounds in the school environment",
                    "point out letter sounds correctly in and out of class",
                    "chant rhymes on letter sounds learnt",
                    "Take pleasure in listening to sounds in the school environment",
                ],
                suggested_activities: [
                    "listen to a variety of sounds from the school environment",
                    "say letter sounds already learnt",
                    "engage in nature walk within the school and identify each sound made (ringing bells, sound from animals and birds, moving vehicles)",
                    "listen to a recorded audio clip on sounds made by familiar things in the environment as they identify them",
                    "tell a variety of sounds heard at home and on the way to school in pairs, in groups and as a whole class",
                    "chant letter sounds and rhymes learnt",
                ],
                key_inquiry_questions: ["What are the differences in sounds within the school environment?"],
            },
            {
                title: "1.2 Articulation of letter sounds",
                learning_outcomes: [
                    "Identify vowel sounds in words",
                    "select vowels from letter sounds",
                    "Articulate all letter sounds from the alphabet",
                    "Take pleasure in articulating vowels and other letter sounds",
                ],
                suggested_activities: [
                    "identify letter sounds from words read by the teacher that relate to school like bag, boy, pen",
                    "list vowels from the letter sounds",
                    "listen to articulation of the vowels from the teacher or a digital device and imitate",
                    "observe charts with all the letters of the alphabet on the wall",
                    "recite letters of the alphabet",
                    "read vowel sounds written on the boards and charts ((a e i o u)",
                    "chant rhymes on vowel sounds",
                    "collaboratively engage in sound articulation games like fishing game",
                ],
                key_inquiry_questions: ["How do different sounds in school help us?"],
            },
            {
                title: "2.1 Letter recognition",
                learning_outcomes: [
                    "read all letters of the alphabet from print in and outside school",
                    "distinguish between the lower case and upper case letters of the alphabet",
                    "chant rhymes to match letter names and letter",
                    "participate with pleasure in letter reading activities",
                ],
                suggested_activities: [
                    "Identify all lettters of the alphabet from print in and out of school",
                    "recognize letters of the alphabet in lower case",
                    "recognize letters of the alphabet in upper case",
                    "listen to letters of the alphabet being read either from a digital device or by the teacher",
                    "imitate reading letters of the alphabet in bits",
                    "individually or in small groups engage in letter recognition games, e g, letter fishing games, letter sorting, letter hunting",
                    "compete in letter recognition games and show fairness in winning and acceptance in losing",
                    "chant rhymes to match letter names with letter sounds (letter a, sound /a/, letter b, sound /b/ ,",
                    "sing songs or recite poems related to letter recognition, while displaying letters",
                ],
                key_inquiry_questions: ["Where can we read letter sounds from?", "Which letter sounds do you like most? Why?"],
            },
            {
                title: "2.2 Picture reading",
                learning_outcomes: [
                    "recognize pictures of things found at school",
                    "demonstrates print awareness by matching pictures with things found in and out of school",
                    "keep participating in activities related to picture reading",
                ],
                suggested_activities: [
                    "view pictures of things found in school either on print, charts or from a digital device",
                    "match pictures with things found in and out of school",
                    "in pairs or groups, talk about the pictures by identifying them and stating use of the objects",
                    "take a nature walk within the classroom and outside the classroom identifying all objects and with guidance on how to be safe",
                    "sing songs related to things found in school",
                ],
                key_inquiry_questions: ["What do you like about your school?"],
            },
            {
                title: "3.1 Letter formation",
                learning_outcomes: [
                    "write the letters of the alphabet in lower case and upper case",
                    "order letters of the alphabet in lower case and upper case in and out of class",
                    "match letters in lower case and upper case correctly",
                    "organise activities related to writing of letters of the alphabet guided by the teacher",
                ],
                suggested_activities: [
                    "observe the teacher demonstrate letter formation in the air, writing boards and imitate",
                    "write the letters of the alphabet in upper and lower case",
                    "in pairs and small group learner to trace and join dots to form letters",
                    "write the letters of the alphabet in upper case and lower case",
                    "match letters in upper case and lower case appropriately",
                    "color and paint letters of the alphabet while singing",
                    "use ICT devices to play letter formation games where applicable",
                    "chant rhymes on letters of the alphabet",
                    "collaboratively model letters of the alphabet in upper case and lower case",
                    "clear working area and wash hands with clean water and soap",
                ],
                key_inquiry_questions: ["What can we do with letters of the alphabet to make them appear good?", "What games relating to letter sounds do you like playing?"],
            },
            {
                title: "3.2 Writing practice",
                learning_outcomes: [
                    "write letters of the alphabet correctly",
                    "Write patterns using letters of the alphabet",
                    "initiate writing activities in and out of school",
                ],
                suggested_activities: [
                    "join dots to make letters of the alphabet",
                    "trace and copy letters of the alphabet correctly",
                    "in pairs or small groups learners to make patterns using letters of the alphabet",
                    "practice writing letters of the alphabet using ICT letter writing games",
                    "write letters of the alphabet in, slate boards, books and any other writing surface",
                    "draw and color pictures of things found in school",
                    "model things found in the school",
                ],
                key_inquiry_questions: ["Which items do we use for writing, coloring and painting?", "Why do we learn letters of the alphabet?"],
            }
        ],
    },
  ],
};
