
/**
 * @fileOverview Curriculum data for Pre-Primary 2 Language Activities.
 * 
 * This file contains the structured curriculum content that will be used
 * by the AI to generate lesson plans, schemes of work, and other resources.
 * This data is extracted from the KICD PP2 Language Activities curriculum design document.
 */

export const pp2LanguageActivitiesCurriculum = {
  grade: "PP2",
  subject: "Language Activities",
  strands: [
    {
      title: "1.0 GREETINGS AND FAREWELL",
      sub_strands: [
        {
          title: "1.1 Greetings and farewell",
          learning_outcomes: [
            "mention reasons why we greet people in our day-to-day life",
            "use greetings correctly while interacting",
            "use farewell words and gestures in social interactions",
            "adopt use of greetings and bidding farewell in daily interactions",
          ],
          suggested_activities: [
            "tell why we greet each other as we interact",
            "role play initiating and responding to greetings",
            "listen to an audio clip on people greeting, watch a video clip on people greeting or read pictures on people greeting and bidding farewell",
            "say how we greet different people (family members, visitors, teachers, school mates, friends) using appropriate words",
            "collaboratively practise bidding farewell using words and gestures",
            "recite poems on greetings and bidding farewell",
            "Sing time related songs on greetings and with reference to different farewell relationships (teacher, mother, peers, visitors)",
          ],
          key_inquiry_questions: [
            "Why do we greet people?",
            "Which words do we use to greet one another?",
          ],
        },
        {
          title: "1.2 Time related greetings and farewell",
          learning_outcomes: [
            "identify time related greetings used in interactions",
            "use time related greetings while interacting with people",
            "bid farewell correctly in relation to time",
            "appreciate use of greetings and bidding of farewell in daily interactions",
          ],
          suggested_activities: [
            "tell how we greet at different times of the day",
            "read pictures or watch a video clip on people greeting and bidding farewell at different times of the day",
            "collaboratively practise greeting at different times of the day",
            "practise bidding farewell at different times of the day",
            "role play greeting and bidding farewell at different times of the day (good morning, good afternoon, good evening)",
            "Sing songs on time related greetings and bidding farewell using words and gestures",
          ],
          key_inquiry_questions: [
            "How do we greet people at different times of the day?",
            "How do bid each other farewell at different times of the day?",
          ],
        },
      ],
    },
    {
      title: "2.0 OUR NEIGHBOURHOOD",
      sub_strands: [
        {
          title: "1.1 Listening for comprehension",
          learning_outcomes: [
            "listen to information for comprehension",
            "answer questions from the listening experience",
            "take pleasure in activities that involve listening and speaking",
          ],
          suggested_activities: [
            "listen to a story about things in the neighbourhood from the teacher or a digital device",
            "retell the story",
            "answer oral questions from a story either collaboratively or as individuals",
            "tell stories about things in and out of the school",
            "recite poems on things found in the neighbourhood (houses, roads, people, plants)",
          ],
          key_inquiry_questions: [
            "What do we do when a story is told?",
            "Which things are found in our surrounding?",
          ],
        },
        {
          title: "1.2 News telling",
          learning_outcomes: [
            "tell news to communicate things that have happened",
            "retell verbal messages for communication",
            "take pleasure in passing verbal messages",
          ],
          suggested_activities: [
            "listen to news from the teacher or pre-recorded news from a digital device using simplified language",
            "collaboratively tell and re-tell news in turns",
            "talk about the importance of neighbours",
            "tell news on happenings in the neighbourhood about people or events",
            "tell news on things observed during a nature walk in their neighbourhood",
            "Sing songs related to things found in the neighbourhood",
          ],
          key_inquiry_questions: [
            "Which things do you see on your way to school?",
            "What do we do when we are not in school?",
          ],
        },
        {
            title: "2.1 Book handling",
            learning_outcomes: [
                "mention ways we care for books",
                "demonstrate book handling skills in and out of school",
                "demonstrate ability to arrange books properly",
                "take pleasure in book handling and storage activities",
            ],
            suggested_activities: [
                "talk about ways of caring for books",
                "role play covering books collaboratively",
                "observe pictures of well-arranged books on shelves or tables",
                "arrange books in bags",
                "arrange and store books properly collaboratively",
                "practise arranging books top side up in shelves or book corner",
                "practise dusting of books with nose covered where there is dust",
                "wash hands after dusting books",
                "Sing songs as they arrange books on shelves, in bags or on tables",
            ],
            key_inquiry_questions: ["How do we take care of our books?"],
        },
        {
            title: "2.2 Reading readiness",
            learning_outcomes: [
                "recognise pictures of things found in the neighbourhood",
                "chant rhymes on letter sounds and letter names",
                "enjoy participating in pre-reading activities",
            ],
            suggested_activities: [
                "identify pictures of things found in the neighbourhood from the writing board, charts, books, flash cards or digital devices (neighbours, buildings, domestic animals, utensils, rivers, roads, play grounds, trees, market)",
                "talk about the pictures collaboratively",
                "read letters of the alphabet in groups and as individuals from charts and flashcards",
                "read letter sounds in pairs and as individuals from charts",
                "chant rhymes on letter sounds and letter names",
            ],
            key_inquiry_questions: [
                "What are the different things found near our school?",
                "Which letter sounds sound almost similar?",
            ],
        },
        {
            title: "2.3 Letter recognition",
            learning_outcomes: [
                "identify different letter names in and out of class",
                "differentiate between upper case and lower case letters of the alphabet",
                "match upper case and lower case letters of the alphabet",
                "take pleasure in chanting rhymes on letter names",
            ],
            suggested_activities: [
                "listen to an audio clip on letter names or read letter names from the board",
                "recall letter names learned",
                "read letters of the alphabet from charts, books, flash cards",
                "match upper case and lower case letters",
                "visit a learning corner with a variety of jumbled letters in different cases and identify each letter name",
                "play letter memory games like fishing game using letter flash cards",
                "chant rhymes collaboratively on letter names",
            ],
            key_inquiry_questions: ["Which letters of the alphabet are almost written the same?"],
        },
        {
            title: "3.1 Letter writing",
            learning_outcomes: [
                "write letters of the alphabet in lower case",
                "write letters of the alphabet in upper case",
                "match in writing lower case and upper case letters",
                "focus on activities related to writing of letters of the alphabet",
            ],
            suggested_activities: [
                "read letters of the alphabet in lower case form charts, books, digital device",
                "read letters of the alphabet in upper case from charts, books, digital device",
                "write letters of the alphabet in the air",
                "write letters of the alphabet in lower case on different materials: books, ground, board, digital device",
                "write letters of the alphabet in upper case on different materials: books, ground, board, digital device",
                "match in writing lower case and upper case letters",
                "model letters of the alphabet in groups using clay, dough or plasticine",
                "clear working area and wash hands with soap and clean water",
                "display work done for peer assessment",
            ],
            key_inquiry_questions: ["How do we tell whether a letter is upper case or lower case?"],
        },
        {
            title: "3.2 Writing practice",
            learning_outcomes: [
                "write correctly and neatly letters of the alphabet",
                "make patterns using letters of the alphabet",
                "take pleasure in activities related to writing of letters of the alphabet",
            ],
            suggested_activities: [
                "colour letters of the alphabet within borders",
                "write letters of the alphabet in lower case on books, digital devices",
                "write letters of the alphabet in upper case on books, digital devices",
                "make patterns on different surfaces using letters of the alphabet collaboratively and as individuals",
                "model letters of the alphabet in pairs",
                "display work done",
            ],
            key_inquiry_questions: ["Why do we make patterns?"],
        }
      ],
    },
    {
        title: "3.0 OUR SCHOOL",
        sub_strands: [
            {
                title: "1.1 Active listening",
                learning_outcomes: [
                    "pay attention to conversations in and out of school",
                    "respond to simple instructions in and out of school",
                    "Enjoy participating in conversations",
                ],
                suggested_activities: [
                    "tell stories and poems while others listen",
                    "re-tell stories told by the teacher and other learners",
                    "view and listen to short clips and imitate",
                    "listen to simple instructions and respond",
                    "take turns in conversations",
                    "view recorded clips of their own conversations as they are appreciated and corrected",
                    "participate in verbal games, poems and songs that involve turn taking",
                ],
                key_inquiry_questions: [
                    "When do you speak during a conversation?",
                    "How do people respond to instructions?",
                ],
            },
            {
                title: "1.2 Self expression",
                learning_outcomes: [
                    "express own needs and ideas verbally in and out of school",
                    "use appropriate vocabulary to express own needs and ideas in and out of school",
                    "actively participate in activities on selfexpression",
                ],
                suggested_activities: [
                    "express own needs (what they require), ideas and thoughts freely",
                    "tell news or talk about what they are doing during school activities (reading, writing, colouring)",
                    "be engaged in short discussions and answering of simple questions",
                    "in pairs and small group to tell news and stories on school activities",
                    "sing songs about their school needs",
                ],
                key_inquiry_questions: [
                    "What can you say about yourself?",
                    "What do we require while in school?",
                ],
            },
            {
                title: "2.1 Print awareness",
                learning_outcomes: [
                    "recognise pictures related to school",
                    "demonstrate awareness of print in and out of school",
                    "show interest in reading in and out of school",
                ],
                suggested_activities: [
                    "read pictures on things found in the school and talk about them",
                    "collaboratively read picture stories to each other and appreciate one another",
                    "read pictures on safe things to do in school and safe and unsafe places in school",
                    "view video depicting stories and be asked to answer questions on the story",
                    "read pictures related to safe and unsafe places in and out of school",
                    "read pictures, letter sounds and names of letters of the alphabet from different materials",
                    "play games on identification of pictures, letter sound and letters of the alphabet",
                ],
                key_inquiry_questions: ["Which pictures do you enjoy reading? Why?"],
            },
            {
                title: "2.2 Reading syllables",
                learning_outcomes: [
                    "join two sounds to read syllables in and out of class (ba-bu, da-du)",
                    "demonstrate ability to read syllables in class",
                    "enjoy participating in activities that involve reading of syllables",
                ],
                suggested_activities: [
                    "Read letter sounds from a chart, writing board, book or digital device",
                    "join 2 sounds, a consonant and a vowel to make syllables",
                    "blend sounds to make syllables, example; ba be bi bo bu, da de di do du",
                    "read and master syllables",
                    "practise reading syllables in pairs and small groups as they correct one another",
                    "play games on syllables like a fishing game using flash cards with syllables",
                ],
                key_inquiry_questions: [
                    "Where can we read letter sounds from in and out of school?",
                    "Which letters of the alphabet can you remember?",
                ],
            },
            {
                title: "3.1 Drawing pictures",
                learning_outcomes: [
                    "identify pictures of objects within the school environment",
                    "draw different objects within the school environment",
                    "colour the drawings using different colours",
                    "show excitement in drawing activities",
                ],
                suggested_activities: [
                    "name things found in the school",
                    "read pictures of things found within the school",
                    "draw pictures of things found within the school environment",
                    "colour the drawings while sharing the colour pencils",
                    "model different things found in school and share the modelling material",
                    "wash hands after modelling",
                    "display the work done for peer assessment and for enhancement of self-efficacy",
                    "sing songs/recite poems in groups related to the things found in the school",
                ],
                key_inquiry_questions: ["Which things are found in our school environment?"],
            },
            {
                title: "3.2 Writing syllables",
                learning_outcomes: [
                    "write syllables in and out of class (ba-bu, ca-cu, da-du)",
                    "demonstrate ability to write syllables properly in and out of class",
                    "participate continuously in activities that involve writing of syllables",
                ],
                suggested_activities: [
                    "read the already learned syllables from charts, books, flash cards, a writing board or a digital device (ba-bu, ca-cu, da-du)",
                    "write the syllables in the air",
                    "join sounds to make syllables in writing (consonants and vowels) collaboratively",
                    "model learned syllables",
                    "wash hands with clean water and soap after modelling",
                    "Colour the learned syllables",
                    "make patterns using syllables",
                    "Display work done",
                    "chant rhymes on syllables",
                ],
                key_inquiry_questions: [
                    "How do we sit when writing?",
                    "Where can we read sounds?",
                ],
            }
        ]
    },
    {
        title: "4.0 OUR MARKET",
        sub_strands: [
            {
                title: "1.1 Polite language",
                learning_outcomes: [
                    "identify polite words used to appreciate, apologise and make requests",
                    "use appropriate vocabulary when making requests, apologising and appreciating (please, excuse me, may I, sorry)",
                    "advocate for use of polite language in social interactions",
                ],
                suggested_activities: [
                    "watch a role play or video clip of people using polite language (please, excuse me, may I, sorry, excuse me and I am sorry) where applicable",
                    "identify words used in polite language from the role play, video clip watched/story told",
                    "role play buying and selling with negotiation of prices (bargaining for better prices of items)",
                    "listen to a story from the teacher on use of polite language",
                    "construct simple sentences using polite language",
                    "sing songs related to market",
                ],
                key_inquiry_questions: [
                    "Which words do we use to request for something?",
                    "Which words do we use to apologise when we wrong someone?",
                ],
            },
            {
                title: "1.2 Passing information",
                learning_outcomes: [
                    "describe a market using simple language",
                    "engage in conversations related to things found in the market to pass information",
                    "take pleasure in passing verbal messages through conversations",
                ],
                suggested_activities: [
                    "talk about a market, what it is and what happens there",
                    "read pictures from charts, books, magazines on people in the market",
                    "watch a video clip on people buying and selling in the market",
                    "collect packaging containers for different items and arrange in the shop corner",
                    "tell short stories about people found in the market",
                    "talk about things bought and sold in the market",
                    "role play conversations between buyer and seller while in the shop corner",
                    "display items sold in the market at the shop corner (containers, sachets)",
                ],
                key_inquiry_questions: ["Why do we buy and sell things at the market?"],
            },
            {
                title: "2.1 Visual discrimination",
                learning_outcomes: [
                    "identify pictures of different items sold in the market",
                    "demonstrate awareness of similarities in things found in the market",
                    "demonstrate awareness of differences in things found in the market",
                    "actively participate in picture reading activities",
                ],
                suggested_activities: [
                    "watch a video clip on things found in the market and people buying and selling",
                    "observe pictures of things found in the market and people in the market buying and selling",
                    "name different goods sold in the market",
                    "sort pictures of different things found in the market",
                    "using pictures, tell similarities in things found in the market: size, colour, shape",
                    "using pictures, tell differences in things found in the market: size, colour, shape",
                    "identify pictures of dirty or rotten items sold in the market that we should not buy",
                    "Sing songs related to activities taking place in the market",
                ],
                key_inquiry_questions: [
                    "Which items do we buy from the market?",
                    "Why do we buy things from the market?",
                ],
            },
            {
                title: "2.2 Reading letters of the alphabet",
                learning_outcomes: [
                    "read letters of the alphabet using their names (A-Z)",
                    "read letter sounds using letters of the alphabet",
                    "chant rhymes to match letter names and letter sounds",
                    "participate in chanting rhymes on letter names and letter sounds",
                ],
                suggested_activities: [
                    "watch an animated clip on letter names and letter sounds",
                    "identify letter names of the alphabet from books, charts, boards, flash cards, digital device",
                    "read the letter sounds in turns from a chart, books, boards, flash cards, digital device",
                    "chant rhymes on letter names and letter sounds in turns and collaboratively in the right order, (Letter a, sound /a /,Letter b, sound /b/……)",
                ],
                key_inquiry_questions: [
                    "Why do we learn letter sounds?",
                    "Which letters of the alphabet do we like most? Why?",
                ],
            },
            {
                title: "2.3 Reading syllables",
                learning_outcomes: [
                    "read syllables by joining 2 letter sounds; fa fe fi fo fu, ga ge gi go gu, ha he hi ho hu",
                    "chant rhymes related to syllables",
                    "focus on chanting rhymes related to syllables reading",
                ],
                suggested_activities: [
                    "listen to recorded syllables from a digital device",
                    "identify written letter sounds",
                    "join two sounds to form syllables",
                    "read the syllables fa fe fi fo fu, ga ge gi go gu, ha he hi ho hu on flash cards, books, charts, writing board, digital device",
                    "chant rhymes on letter sounds collaboratively and as individuals while others listen to and appreciate the effort by clapping",
                    "play games related to letter sounds and syllables using flash cards",
                ],
                key_inquiry_questions: ["Where can we read letter sounds from?"],
            },
            {
                title: "3.1 Eye-hand Coordination",
                learning_outcomes: [
                    "write patterns using letters of the alphabet",
                    "demonstrate eye-hand coordination when writing letters of the alphabet",
                    "choose to participate in activities that involve eye-hand coordination (reading using a pen or finger and writing)",
                ],
                suggested_activities: [
                    "practise writing letters on floor, on a writing board, on air, on books, a digital device",
                    "colour letters of the alphabet",
                    "colour pictures of things found in the market",
                    "model letters of the alphabet using clay, plasticine, dough",
                    "model things found in the market",
                    "wash hands after modelling",
                    "paint and print letters of the alphabet and wash hands",
                    "trace letters of the alphabet",
                    "practise fixing letter puzzles collaboratively to enhance eye-hand coordination",
                    "display work done",
                    "play digital games on letters of the alphabet that involve the manipulation of a digital device",
                ],
                key_inquiry_questions: ["How can we form letters of the alphabet? (writing, modelling, painting, fixing puzzles, writing in the air)"],
            },
            {
                title: "3.2 Writing letters of the alphabet",
                learning_outcomes: [
                    "write letters of the alphabet in the lower case (small letters)",
                    "write letters of the alphabet in upper case (capital letters)",
                    "match letters of the alphabet (lower and upper case)",
                    "attempt exercises related to writing letters of the alphabet",
                ],
                suggested_activities: [
                    "read letters of the alphabet from a book, chart, board, cards and/or from a digital device",
                    "trace letters of alphabet in both cases",
                    "copy letters of the alphabet in lower case",
                    "copy letters of the alphabet in upper case",
                    "practice writing letters of the alphabet using a digital device",
                    "make patterns using letters of the alphabet collaboratively",
                    "match letters of the alphabet in writing (lower and upper case)",
                    "model letters of alphabet in both cases",
                    "display their work to the class",
                ],
                key_inquiry_questions: ["Which materials do we use for writing?"],
            },
            {
                title: "3.3 Writing syllables",
                learning_outcomes: [
                    "Write syllables using letter sounds; fa – fu, ga – gu, ha – hu",
                    "Demonstrate ability to write syllables independently",
                    "Participate continuously in activities that involve writing of syllables",
                ],
                suggested_activities: [
                    "read syllables from a chart, book, flash cards, board or a digital device",
                    "engage in blending sounds to make syllables (fa fe fi fo fu, ga ge gi go gu, ha he hi ho hu)",
                    "practice writing syllables collaboratively on the writing board",
                    "write syllables on a digital device where applicable",
                    "write syllables on own books while reading aloud each syllable",
                    "practice writing activities of learnt syllables on flashcards",
                    "compete in syllable writing games while encouraging fairness in winning and accepting in losing",
                ],
                key_inquiry_questions: [
                    "Which items bought from the market have syllable ‘ba’?",
                    "Which materials do we need in writing syllables?",
                ],
            }
        ]
    },
    {
      title: "5.0 ANIMALS",
      sub_strands: [
        {
          title: "1.1 Auditory discrimination",
          learning_outcomes: [
            "identify all the sounds of the letters of the alphabet",
            "distinguish closely related letter sounds in the alphabet",
            "imitate sounds made by different animals kept at home",
            "develop interest in listening to sounds in the environment",
          ],
          suggested_activities: [
            "listen to letter sounds articulation from the teacher or an audio recording/video clip",
            "articulate/read letter sounds correctly",
            "articulate closely related letter sounds as demonstrated: /p/ and /b/ ,/t/ and /d/, /k/ and /c/, /l/ and /r/, /f/ and /v/, /s/ and/z/, /w/ and /y/, /k/ and /q/",
            "play letter sound games collaboratively",
            "listen to an audio clip on sounds produced by different animals",
            "listen to sounds made by animals during a nature walk around the school neighbourhood",
            "Imitate sounds made by animals",
            "sing songs and recite poems on sounds made by animals",
          ],
          key_inquiry_questions: [
            "Which letter sounds almost sound the same?",
            "Which animal sounds do you hear within our school?",
          ],
        },
        {
          title: "1.2 Audience awareness",
          learning_outcomes: [
            "explain when to speak loudly when addressing audience",
            "explain when to speak softly when speaking to audience",
            "exhibit audience awareness by varying intonation when speaking",
            "participate actively and audibly in speaking activities to convey message to others",
          ],
          suggested_activities: [
            "say when one is supposed to speak loudly when passing message",
            "say when one is supposed to speak softly when passing message",
            "give reasons why some people may speak softly even when talking to many people (sickness, shyness, fear, low self-esteem)",
            "listen to the teacher or a recorded clip telling a story on the importance of animals (what animals give us)",
            "re-tell the stories audibly and with clarity while being recorded for replay",
            "listen to the recorded pieces of their own clip",
            "react to the recorded clip in reference to audience awareness",
          ],
          key_inquiry_questions: [
            "How should we speak to be heard?",
            "How do the animals kept at home help us?",
          ],
        },
        {
          title: "2.1 Visual memory",
          learning_outcomes: [
            "recall letters of the alphabet in and out of class",
            "demonstrate ability to recognise pictures of wild animals",
            "participate actively in activities that involve recalling",
          ],
          suggested_activities: [
            "visit a learning corner within the class to observe different objects",
            "settle back to seats and mention the objects observed",
            "read loudly letters of the alphabet from charts, books or digital devices using letter names",
            "chant letters of the alphabet collaboratively in the absence of a chart or writings of the same",
            "tell names of wild animals observed during a visit to game park, watched on media or seen on pictures collaboratively",
            "get involved in visual memory games like a fishing game on animals drawn on flashcards",
            "play letter memory games",
          ],
          key_inquiry_questions: ["How are some wild animals dangerous?"],
        },
        {
          title: "2.2 Reading syllables",
          learning_outcomes: [
            "recall syllables learnt earlier",
            "join sounds to read syllables ( ja-ju, ka-ku and la- lu)",
            "Perform activities that involve reading of syllables",
          ],
          suggested_activities: [
            "watch video clip on reading of syllables",
            "revise read syllables",
            "join sounds to form syllables (ja-ju, ka-ku and la- lu)",
            "blend sounds to read syllables …ja, ka, la",
            "practise reading syllables collaboratively with some guiding others",
            "chant rhymes on syllables",
            "get involved in a variety of activities to practice reading syllables",
          ],
          key_inquiry_questions: [
            "Which are the five biggest wild animals?",
            "Which are the fastest wild animals?",
          ],
        },
        {
          title: "3.1 Pattern writing",
          learning_outcomes: [
            "write simple patterns in the air using letters of the alphabet",
            "hold a writing tool appropriately when writing",
            "take pleasure in simple pattern writing activities in and out of class",
          ],
          suggested_activities: [
            "recite the letters of the alphabet collaboratively taking turns",
            "observe a demonstration on how to write a pattern",
            "hold a writing tool appropriately",
            "copy simple patterns",
            "practise writing simple patterns by joining letters of the alphabet",
            "compete on the speed of writing patterns",
            "display patterns written",
            "sing songs and watch video clips on pattern writing",
          ],
          key_inquiry_questions: [
            "Which tools do we use for pattern writing?",
            "Why do we write patterns?",
          ],
        },
        {
          title: "3.2 Writing syllables",
          learning_outcomes: [
            "write syllables in and out of class (ja-ju, ka-ku and la-lu)",
            "demonstrate ability to write syllables properly in and out of class",
            "show excitement in using basic tools for writing activities in and out of school",
          ],
          suggested_activities: [
            "write letters of the alphabet",
            "join dots to make syllables",
            "copy syllables properly in and out of class",
            "write syllables on the board and on books",
            "make patterns using syllables",
            "model syllables while sharing the modelling materials (plasticine and or clay)",
            "practise writing syllables on ICT devices where applicable ,others write on board, ground, books, cards and board",
            "display work done",
          ],
          key_inquiry_questions: ["Why do we write syllables?"],
        },
      ],
    },
    {
      title: "6.0 WEATHER CONDITIONS",
      sub_strands: [
        {
          title: "1.1 Auditory memory",
          learning_outcomes: [
            "recall learned letter sounds and syllables in and out of class",
            "demonstrate ability to recognise sounds associated with different weather conditions",
            "actively participate in activities that involve recognition of sounds",
          ],
          suggested_activities: [
            "recognise letters of the alphabet",
            "identify syllables",
            "listen to the teacher presenting learnt letter sounds and syllables",
            "listen to audio clips on learnt letter sounds and syllables",
            "imitate sounds and syllables as presented by the teacher or/and audio clips",
            "watch a video clip on sounds associated with rainy and windy weather conditions",
            "role play windy and rainy weather conditions producing sounds associated with the two",
          ],
          key_inquiry_questions: ["Which letter sounds can you remember?"],
        },
        {
          title: "1.2 Observation skills",
          learning_outcomes: [
            "name different weather conditions",
            "describe weather conditions observed",
            "express appreciation of different weather conditions",
          ],
          suggested_activities: [
            "take a nature walk outside classroom to observe weather",
            "watch a video clip on the effect of different weather conditions",
            "tell the weather conditions observed",
            "name different weather conditions",
            "talk about observed weather conditions",
            "identify different activities done under different weather conditions",
            "identify negative effects of weather conditions",
            "role play a rainy day learner carrying umbrellas",
            "sing songs related to different weather conditions",
          ],
          key_inquiry_questions: [
            "How is the weather today?",
            "Which clothes do we wear on a rainy day?",
          ],
        },
        {
          title: "2.1 Visual discrimination",
          learning_outcomes: [
            "identify different pictures of weather symbols",
            "match and pair pictures of weather symbols and activities taking place",
            "enjoy participating in activities that involve differentiating objects based on what is observed",
          ],
          suggested_activities: [
            "view pictures depicting different weather conditions from a digital device, flash cards or charts and books",
            "talk about the pictures of different weather conditions",
            "identify pictures of different clothes worn in different weather conditions",
            "tell why dress differently in different weather conditions",
            "match and pair pictures of weather symbols with activities taking place",
            "recite poems on weather conditions",
          ],
          key_inquiry_questions: [
            "How can you describe the weather today?",
            "Which clothes do we wear on a hot day?",
          ],
        },
        {
          title: "2.2 Reading syllables",
          learning_outcomes: [
            "recall syllables learned earlier",
            "join letter sounds to read syllables (ma-mu, na-nu and pa-pu)",
            "take pleasure when performing activities that involve reading of syllables",
          ],
          suggested_activities: [
            "read out syllables learned",
            "view video clip/listen to audio clip on reading of syllables",
            "re-read syllables viewed",
            "join sounds to form new syllables (ma-mu, na-nu and pa-pu)",
            "blend letter sounds to read syllables e g, ta, pa, da ma",
            "practice reading syllables collaboratively",
            "sing songs on syllables",
            "get involved in a variety of activities to practice reading syllables",
          ],
          key_inquiry_questions: ["Which syllables can you recall?"],
        },
        {
          title: "3.1 Recording skills",
          learning_outcomes: [
            "recognise observed weather con1ditions",
            "Record observed weather conditions in a simple weather chart",
            "Actively participate in activities related to weather conditions",
          ],
          suggested_activities: [
            "Observe different weather conditions on a video clip",
            "Observe weather conditions outside the classroom on a nature walk",
            "Recognise pictures on weather symbols such as rainy, windy, sunny and cloudy from charts and books",
            "Tick weather symbol observed on a chart on the particular day, (the weather chart should have 5 days of a week, from Monday to Friday and the four weather conditions symbols for morning session and afternoon session. The learner should tick one symbol every morning after observation and one symbol every afternoon on the same day after observing weather for the 5 days)",
            "Display recorded weather chart at the end of the week",
          ],
          key_inquiry_questions: ["What do we wear on a rainy day?"],
        },
        {
          title: "3.2 Writing syllables",
          learning_outcomes: [
            "recognise syllables in and out of class (ma-mu, na-nu and pa-pu)",
            "write syllables neatly in and out of class",
            "with pleasure use basic tools for writing activities in and out of school",
          ],
          suggested_activities: [
            "write letters of the alphabet",
            "join dots to make syllables",
            "copy syllables properly in and out of class",
            "write syllables on the board and on books",
            "collaboratively make patterns using syllables",
            "display work done",
            "practise writing syllables on ICT devices where applicable ,others write on board, ground, books, cards and board",
          ],
          key_inquiry_questions: [
            "How do we sit when writing?",
            "Which tools do we use for writing syllables?",
          ],
        },
      ],
    },
    {
      title: "7.0 WATER",
      sub_strands: [
        {
          title: "1.1 Naming",
          learning_outcomes: [
            "name different places and ways of getting water",
            "identify different containers for storing water",
            "demonstrate awareness of uses of water in our daily lives",
            "appreciate the importance of water in our daily lives",
          ],
          suggested_activities: [
            "watch a video clip related to different sources of water",
            "mention different ways and places of getting water (sources)",
            "talk about safety precautions surrounding water sources",
            "observe containers for storing water during a nature walk (water tank, pots, jerricans, buckets, drums)",
            "name different containers used for storing water",
            "talk about uses of water",
            "role play uses of water (cooking, drinking, washing)",
            "recite poems on uses to water",
          ],
          key_inquiry_questions: ["How do we use water at home?"],
        },
        {
          title: "1.2 Articulating letter sounds",
          learning_outcomes: [
            "articulate letter sounds using letters of the alphabet in and out of school (a-z)",
            "demonstrate awareness of letter sound correspondence in and out of class",
            "take pleasure in activities relating to articulation of letters of the alphabet",
          ],
          suggested_activities: [
            "view and listen to letter sounds from audio or video clips that enhance letter sound articulation",
            "in turns, identify the letter sounds using letters of the alphabet from charts and flashcards",
            "collaboratively match letter sounds with corresponding names of objects whose name begin with the letter sound ( a for apple, b for boy…)",
            "chant rhymes on letter sounds",
          ],
          key_inquiry_questions: ["Which letter sounds almost sound similar?"],
        },
        {
          title: "2.1 Picture Reading",
          learning_outcomes: [
            "name activities that involve uses of water",
            "demonstrate ability to interpret illustrated uses of water",
            "show excitement in activities related to picture reading",
          ],
          suggested_activities: [
            "view a video clip on different uses of water where applicable",
            "talk about different uses of water mentioning activities where water is used (cooking, bathing, washing, drinking, farming)",
            "observe uses of water during a nature walk in the school neighbourhood",
            "observe pictures depicting different uses of water",
            "collaboratively read pictures illustrating uses of water on charts, books while helping one another interpret correctly",
            "role play uses of water (pretend to cook, drink, wash, brush teeth wash handkerchief, bath)",
            "sing songs, recite poems on uses of water",
          ],
          key_inquiry_questions: ["How do we use water at home?"],
        },
        {
          title: "2.2.Reading syllables",
          learning_outcomes: [
            "recall the syllables learnt",
            "demonstrate ability to read syllables in and out of class (ra – ru, sa – su, ta – tu)",
            "acknowledge the use of syllables in daily communication",
          ],
          suggested_activities: [
            "listen to an audio clip on reading of syllables",
            "re-read syllables already learned",
            "join sounds to form new syllables (ra – ru, sa – su, ta – tu)",
            "blend sounds to make syllables … ra, re, ri ,ro, ru",
            "read syllables collaboratively and individually",
            "practice reading syllables collaboratively",
            "chant rhymes on syllables",
          ],
          key_inquiry_questions: ["Which words begin with the syllable ‘ra-’?"],
        },
        {
          title: "2.3 Word formation",
          learning_outcomes: [
            "identify syllables and sounds in preparation for reading words",
            "blend syllables and sounds to form three letter words in and out of school",
            "read three letter words in and out of school",
            "perform activities that involve reading of three letter words in and out of school",
          ],
          suggested_activities: [
            "listen to audio clips on word formation where syllables and sounds are joined and read out",
            "read sounds and syllables from charts, books and other materials",
            "blend syllables and sounds to form three words orally, example ca +t =cat, pe+g =peg, po + t =pot",
            "read three letter words",
            "practice reading three letter words collaboratively",
            "play games in forming three letter words",
          ],
          key_inquiry_questions: [
            "What do we need to do in order to read words?",
            "How do we read words?",
          ],
        },
        {
          title: "3.1 Hand writing",
          learning_outcomes: [
            "recognise different syllables and sounds in preparation for writing words",
            "join syllables and sounds to form three letter words",
            "write three letter words in and out of class",
            "discover new ideas related to hand writing",
          ],
          suggested_activities: [
            "explain how a good hand writing should be",
            "observe charts and books with good hand writing where letters are well shaped, arranged and of good size",
            "observe the shaping of letters from a digital device",
            "read syllables from any available source; digital device, books, charts",
            "read three letter words from any available source; digital device, books, charts",
            "practice writing three letter words collaboratively and later individually. For example; bat, tab, mat / bet, met, pet",
            "display written words for others to read",
            "blend sounds and read them aloud as they write them down in books",
          ],
          key_inquiry_questions: ["Why are we supposed to write neatly?"],
        },
        {
          title: "3.2 Writing syllables",
          learning_outcomes: [
            "write syllables in and out of class (ra-ru, sa-su and ta-tu)",
            "demonstrate ability to write syllables in and out of class",
            "show excitement in using basic tools for writing activities in and out of class",
          ],
          suggested_activities: [
            "write letters of the alphabet",
            "copy syllables already learned properly",
            "write syllables on different surfaces: the board, charts, ground and on books",
            "practise writing syllables on ICT devices where applicable",
            "make patterns using syllables",
            "display work done",
            "collaboratively chant rhymes on syllables as they write them",
          ],
          key_inquiry_questions: [
            "Which do we need to write syllables?",
            "Why do we write syllables?",
          ],
        },
      ],
    },
    {
      title: "8.0 TIME",
      sub_strands: [
        {
          title: "1.1 News telling",
          learning_outcomes: [
            "tell news on daily happenings with an ease",
            "narrate events as they happen in a sequence to communicate order and time",
            "actively contribute in activities on news telling",
          ],
          suggested_activities: [
            "watch a video clip indicating activities done at different times of the day",
            "observe and talk about pictures showing activities done at different times of the day",
            "talk about different activities we do every day from morning to evening: waking up, taking breakfast, preparing for school, going to school, break time, lunch, evening, sleeping)",
            "narrate in pairs the day’s happenings, like what they did before coming to school and what they will do after school",
            "sing songs related to time",
          ],
          key_inquiry_questions: [
            "What do we do before coming to school?",
            "What do we do every day when not coming to school?",
          ],
        },
        {
          title: "1.2 Passing information on time",
          learning_outcomes: [
            "identify vocabulary related to time (morning, evening, yesterday, today, tomorrow)",
            "use vocabulary related to time to make simple sentences",
            "narrate stories of daily happenings",
            "value the importance of passing information for communication",
          ],
          suggested_activities: [
            "watch a video clip on daily routine, listen to audio clip on stories of time",
            "identify and talk about activities related time using periods, like morning and evening, days like yesterday and tomorrow",
            "in turns, make simple sentences using time vocabulary like today, yesterday, tomorrow, morning, evening",
            "react on sentences made by each",
            "in groups, role play activities done at different times of the day",
            "tell stories about chores that take place at home before coming to school ,at school and in the evening",
            "sing songs related to time",
          ],
          key_inquiry_questions: [
            "What do you do before coming to school?",
            "What do you do on the days we do not come to school?",
          ],
        },
        {
          title: "1.3 Story telling",
          learning_outcomes: [
            "mention common public holidays",
            "identify days of the week",
            "role play activities done on different days of the week",
            "uphold celebration of various public holidays",
          ],
          suggested_activities: [
            "identify common public holidays: -Christmas, Easter and mashujaa (christians), -Id ul Fitr and Mashujaa (Muslims), -Diwali and Mashujaa (Hindus)",
            "watch a short video clip on people celebrating on a public holiday",
            "tell stories on how the public holidays are celebrated",
            "role play religious public holidays and Mashujaa day and any other public holiday they are familiar with",
            "identify days of week (Sunday – Saturday)",
            "tell stories on different days of the week",
            "in groups, role play activities done on different days of the week (market, school, church / mosque)",
            "sing songs related to Mashujaa Day",
            "sing songs related to days of the week",
          ],
          key_inquiry_questions: [
            "Which days do we like celebrating? Why?",
            "What activities do we do on our worship day?",
          ],
        },
        {
          title: "2.1 Reading syllables",
          learning_outcomes: [
            "recall syllables learnt earlier in and out of class",
            "read blended sounds to make syllables",
            "identify syllables in and out of class (va-vu,wa-wu,za-zu)",
            "discover activities that involve reading of syllables",
          ],
          suggested_activities: [
            "read syllables from charts, books or digital device",
            "recite syllables",
            "read blended sounds to make syllables e g, ta, pa, da ma",
            "read syllables (va-vu,wa-wu,za-zu) in and out of class",
            "read the syllables collaboratively",
            "chant rhymes on syllables",
          ],
          key_inquiry_questions: ["How do we blend sounds to make syllables?"],
        },
        {
          title: "2.2 Reading three letter words",
          learning_outcomes: [
            "identify syllables and sounds for reading purpose",
            "blend syllables and sounds to form three letter words in and out of class",
            "read three letter words in and out of school",
            "perform activities that involve reading three letter words in and out of class",
          ],
          suggested_activities: [
            "listen to an audio clip with syllables",
            "read syllables and sounds from charts, books and other materials",
            "blend syllables and sounds to form three words example run, bat, sit",
            "read three letter words",
            "practice reading three letter words collaboratively",
          ],
          key_inquiry_questions: ["How do we read syllables?"],
        },
        {
          title: "3.1 Writing three letter words",
          learning_outcomes: [
            "read three letter words in and out of school",
            "join syllables and sounds to form three letter words in writing",
            "perform activities that involve formation of three letter words",
          ],
          suggested_activities: [
            "read three letter words from a chart or digital device",
            "blend syllables and sounds to read three letter words from different materials, (cat, run, bag, pen, set)",
            "join syllables and sounds to write three letter words",
            "write three letter words by arranging cards of syllables and sounds on a pocket chart",
            "display work done",
            "practise writing three letter words on ICT devices or on board, ground, books, cards",
          ],
          key_inquiry_questions: ["How do we sit when writing?"],
        },
      ],
    },
    {
      title: "9.0 TRANSPORT",
      sub_strands: [
        {
          title: "1.1 Naming",
          learning_outcomes: [
            "name different means of transport",
            "tell commonly used means of transport within the environment",
            "describe movement of different means of transport",
            "enjoy imitating the movement of different means of transport",
          ],
          suggested_activities: [
            "tell common means of transport commonly used within the environment (cars, bicycles, tuktuk, SGR/train, motorcycles, aero planes, donkeys, carts)",
            "view a video clip on different means of transport or read pictures from cards, books, charts on means of transport",
            "collaboratively talk about different means of transport in relation to viewed video clip, or read pictures",
            "listen to different sounds made by different means of transport from the environment while on a nature walk within the school",
            "imitate sounds made by different means of transport",
            "Talk about safe practices when using different means of transport",
            "sing songs, recite poems and/or chant rhymes related to different means of transport",
          ],
          key_inquiry_questions: [
            "How do we go to school and back home?",
            "How do people move from one place to another?",
          ],
        },
        {
          title: "1.2 News telling",
          learning_outcomes: [
            "tell news on experiences of travelling using different means of transport",
            "tell short stories on means of transport observed on the way to school",
            "demonstrate ability to tell news on daily experiences",
            "appreciate singing songs on different means of transport",
          ],
          suggested_activities: [
            "listen to news from a peer, teacher, parent, neighbor and retell them",
            "role-play telling and listening to news in groups",
            "talk about different means of transport used",
            "report different means of transport seen on the way to school",
            "sing songs and recite poems related to different means of transport",
          ],
          key_inquiry_questions: [
            "How do people move from one place to another?",
            "What happens when one is travelling?",
          ],
        },
        {
          title: "2.1 Picture reading",
          learning_outcomes: [
            "recognize names of pictures on different means of transport",
            "tell differences between various means of transport",
            "match pictures of people working in the transport sector with the different means of transport",
            "enjoy playing games with pictures on means of transport",
          ],
          suggested_activities: [
            "read pictures on different means of transport on charts, books or digital devices",
            "in groups or pairs tell the differences between various means of transport. Examples air, road, railway line, foot paths",
            "identify people with uniform and different protective working clothes in the transport sector examples, driver, captain, pilot, touts, cyclists",
            "match pictures of people with their relevant means of transport",
            "play games on picture identification",
            "play a fishing game on flashing of pictures with people or means of transport",
          ],
          key_inquiry_questions: ["Which kind of pictures have you come across?"],
        },
        {
          title: "2.2 Reading of three letter words",
          learning_outcomes: [
            "recognize sounds, syllables and 3 letter words",
            "join syllables and single sounds to form words",
            "arrange sounds correctly on a pocket chart to form 3 letter words",
            "enjoy participating in activities related to reading of syllables and 3 letter words",
          ],
          suggested_activities: [
            "read sounds, syllables, and 3 letter words on charts, board, cards, from digital device",
            "chant rhymes on letter sounds",
            "read syllables on charts, board, cards, from digital device",
            "join syllables and sounds to form words (blending sounds) in pairs, groups and as individuals",
            "arrange syllables and sounds correctly to form 3 letter words in pairs",
            "play look and say game on silent blending and reading aloud of 3 letter words",
          ],
          key_inquiry_questions: [
            "Which means of transport do people around use?",
            "What is the difference between a bus and a bicycle?",
          ],
        },
        {
          title: "3.1 Picture colouring",
          learning_outcomes: [
            "identify pictures on different means of transport correctly",
            "draw pictures to reflect different means of transport",
            "colour drawn pictures appropriately",
            "enjoy participating in drawing and colouring activities",
          ],
          suggested_activities: [
            "read pictures on different means of transport on charts, books, board and on digital devices",
            "colour drawn pictures on means of transport: buses, van, cars, bicycles, aeroplane, donkey, carts, motorbike",
            "draw pictures on different means of transport",
            "model cars, ship, bicycle, vans, buses in pairs and in group",
            "display drawn, coloured and modelled work",
            "sing songs as they colour pictures",
          ],
          key_inquiry_questions: ["Which materials do we use when colouring?"],
        },
        {
          title: "3.2 Writing practice",
          learning_outcomes: [
            "write letters of the alphabet in the right sequence",
            "write syllables by joining consonants and vowels",
            "write patterns using syllables",
            "form three letter words using syllables and sounds",
            "show excitement in writing activities in and out of class",
          ],
          suggested_activities: [
            "read letters of the alphabet in upper case and lower case",
            "clear working area and wash hands with soap and clean water",
            "write the letters in upper and lower case on a digital device",
            "read letter sounds and syllables in groups and pairs",
            "write letter sounds and syllables",
            "join syllables and sounds and make 3 letter words in pairs",
            "make patterns using syllables",
            "write the patterns repeatedly",
            "model letters of the alphabet clear working area and wash hands with soap and water",
            "chant rhymes on letter sounds while writing",
          ],
          key_inquiry_questions: ["What do you do to make a three letter word?"],
        },
      ],
    },
  ],
};
