
/**
 * @fileOverview Curriculum data for Pre-Primary 2 Environmental Activities.
 * 
 * This file contains the structured curriculum content that will be used
 * by the AI to generate lesson plans, schemes of work, and other resources.
 * This data is extracted from the KICD PP2 Environmental Activities curriculum design document.
 */

export const pp2EnvironmentalActivitiesCurriculum = {
  grade: "PP2",
  subject: "Environmental Activities",
  strands: [
    {
      title: "1.0 Myself",
      sub_strands: [
        {
          title: "1.1 External Body Parts",
          learning_outcomes: [
            "name the external body parts for self-awareness",
            "identify the external body parts for self-awareness",
            "appreciate one's body part for self-esteem",
          ],
          suggested_activities: [
            "mention external body parts (head, mouth and nose)",
            "recite poems on body parts",
            "sing songs about body parts",
            "story telling about external body parts",
            "picture reading the external body parts",
            "draw the external body parts",
            "play games on body parts",
            "model the external body parts",
            "tear along the pictures of external body parts",
            "paste cut out pictures of external body parts",
            "watch video clips of external body parts while observing safety",
          ],
          key_inquiry_questions: ["Why do we have body parts?"],
        },
        {
          title: "1.2 Uses of Body Parts",
          learning_outcomes: [
            "identify body parts for familiarization",
            "tell the uses of body parts for self-awareness",
            "appreciate one’s body parts for self-esteem",
          ],
          suggested_activities: [
            "recognize external body parts (mouth, eyes and ears)",
            "touch as they name body parts",
            "watch videos of external body parts",
            "observe different pictures depicting people performing various actions and which body parts are in use",
            "name the uses of body parts",
            "recite poems about uses of the body parts",
            "sing songs on uses body parts",
            "play games as they mention uses of body parts",
            "discuss about the uses of body parts in groups",
            "news tell on the uses of body parts",
            "role play on the uses of body parts",
          ],
          key_inquiry_questions: ["How do we use body parts?"],
        },
        {
          title: "1.3 Cleaning Nose",
          learning_outcomes: [
            "name the items used to clean the nose in and out of school",
            "wipe the nose appropriately",
            "acknowledge the need to clean the nose appropriately",
          ],
          suggested_activities: [
            "mention the items used to clean the nose",
            "Identifying items used to clean the nose",
            "sing songs on cleaning nose",
            "recite poems about cleaning the nose",
            "use a clean handkerchief",
            "draw and colour handker",
            "practice wiping their nose",
            "cover their nose while sneezing",
            "discuss the importance of cleaning the nose using a clean handkerchief",
            "observe videos clips on cleaning the nose",
            "improvise a handkerchief",
          ],
          key_inquiry_questions: [
            "How do we clean our nose?",
            "Why do we clean our nose?",
          ],
        },
        {
          title: "1.4 Dressing",
          learning_outcomes: [
            "name clothes worn in and out of school",
            "dress and undress in and out school according to different weather conditions",
            "put on shoes properly in and out of school",
            "value one’s clothes for self-esteem",
          ],
          suggested_activities: [
            "identify clothes worn in and out of school",
            "talk about clothes worn in and out of school in groups",
            "sort and group clothes worn in and out of school according to different weather conditions",
            "view video clips on clothes worn in and out of school",
            "read pictures of clothes worn in and out of school",
            "colour pictures of clothes",
            "dress and undress dolls.",
            "practice putting on clothes(sweater, jackets, shirts, shorts, skirts, blouses)",
            "button and unbutton shirts and blouses",
            "Zip and unzip",
            "practice putting on shoes and socks",
            "tying shoe laces",
            "sing songs about clothes in and out of school",
            "recite poems about clothes worn in and out of school",
          ],
          key_inquiry_questions: ["How do we dress on clothes?"],
        },
      ],
    },
    {
      title: "2.0 Our Family",
      sub_strands: [
        {
          title: "2.1 Food Eaten",
          learning_outcomes: [
            "name types of food eaten by family members",
            "identify different types of foods for healthy living",
            "Observe table manners when eating food for good etiquette",
            "appreciate different types of food eaten by the family members",
          ],
          suggested_activities: [
            "mention different types of food eaten by the family members",
            "talk about different types of food eaten by the family members",
            "listen to stories of different types of food eaten by the family members",
            "Sing songs on different types of food eaten by the family members",
            "Recite poems on different types of food eaten by the family members",
            "wash fruits before eating",
            "talk about dos and don'ts while eating in groups",
            "draw different types of food eaten by the family members",
            "Colour different types of food eaten by the family members",
            "Match and pair pictures of fruits eaten by the family members",
            "watch video clips on table manners",
            "role play eating food while observing table manner",
          ],
          key_inquiry_questions: [
            "Why do we eat food?",
            "What types of food do you eat?",
          ],
        },
        {
          title: "2.2 Importance of Eating Food",
          learning_outcomes: [
            "tell the importance of eating food for healthy living",
            "talk about the importance of eating clean food",
            "wash fruits before eating for healthy living",
            "appreciate the importance of eating food",
          ],
          suggested_activities: [
            "mention the importance of eating clean food",
            "watch video clips on the importance of eating food",
            "Story tell the importance of eating food",
            "recite poems on the importance of eating food",
            "role play on importance of eating clean food",
            "eat snacks and fruits in groups",
            "sing songs on the importance of eating food",
            "dramatize on the importance of eating food",
            "picture reading on the importance of eating food",
            "observe different pictures",
          ],
          key_inquiry_questions: [
            "Why do we eat food?",
            "How do we clean fruits before eating?",
          ],
        },
      ],
    },
    {
      title: "3.0 Our Home",
      sub_strands: [
        {
          title: "3.1 Houses Found at Home",
          learning_outcomes: [
            "name houses at home for familiarity",
            "identify different houses at home",
            "tell the uses of houses found at home",
            "recognise the various types of houses at home",
          ],
          suggested_activities: [
            "tell different houses at home,(toilet, latrine, kitchen, poultry, granary)",
            "identify houses found at home in pairs",
            "view video clips of houses at home",
            "observe charts of houses at home",
            "draw houses at home",
            "Colour houses at home",
            "model houses at home",
            "paint houses at home",
            "sing songs on the uses of houses at home in groups",
            "talk about uses of houses at home in groups",
            "recite poems on the uses of houses at home.",
            "Use clay or plasticine to model simple house found at home in groups",
          ],
          key_inquiry_questions: [
            "Why do we have houses at home?",
            "What types of houses do we have at home?",
          ],
        },
        {
          title: "3.2 Work Done at Home",
          learning_outcomes: [
            "name work done at home for familiarization",
            "talk about the importance of work done at home",
            "practice work done at home",
            "appreciate work done at home for self-enjoyment",
          ],
          suggested_activities: [
            "mention work done at home",
            "talk about work done at home",
            "news tell about different work done at home",
            "Picture read on different work done at home.",
            "walk around the school to identify work done by people",
            "discuss about the importance of work done at home",
            "sing songs about work done at home",
            "recite poems on work done at home",
            "watch video clip on work done at home",
            "imitate work done at home",
            "role play work done by people at home",
          ],
          key_inquiry_questions: ["Why do people work?"],
        },
        {
          title: "3.3 Domestic Animals",
          learning_outcomes: [
            "name domestic animals at home",
            "identify domestic animals found at home",
            "care for the domestic animals at home",
            "value domestic animals at home",
          ],
          suggested_activities: [
            "observe pictures of domestic animals found at home",
            "watch video clips on domestic animals",
            "model domestic animals",
            "draw domestic animals",
            "paint pictures of domestic animals",
            "trace domestic animals",
            "cut and paste pictures of domestic animals",
            "Colour pictures of animals",
            "go for a nature walk to observe domestic animals",
            "engage in role play about domestic animals",
            "match and pair pictures of domestic animals",
            "sort and group pictures of domestic animals found at home",
            "feed the domestic animals",
            "Water the domestistic animals",
            "recite poems on domestic animals",
            "sing songs about domestic animals",
          ],
          key_inquiry_questions: ["Why do we have animals at home?"],
        },
      ],
    },
    {
      title: "4.0 Our Neighbourhood",
      sub_strands: [
        {
          title: "4.1 Families in Our Neighborhood",
          learning_outcomes: [
            "name families in the neighborhood for harmonious living",
            "talk about the importance of families in our neighborhood",
            "appreciate the families in the neighborhood for harmonious living",
          ],
          suggested_activities: [
            "mention families in the neighborhood",
            "talk about families in the neighborhood in groups",
            "dramatize families in the neighborhood",
            "Discuss about the importance of families in the neighbourhood",
            "sing songs about family members in the neighborhood",
            "recite poems in the families in the neighborhood",
          ],
          key_inquiry_questions: ["Who is our neighbors?"],
        },
        {
          title: "4.2 Buildings in The Neighbourhood",
          learning_outcomes: [
            "name different buildings in the neighbourhood",
            "talk about the uses of buildings in neighbourhood",
            "appreciate buildings in the neighbourhood",
          ],
          suggested_activities: [
            "identify buildings in the neighbourhood,(market, shop, hospital, school, church, mosque, temple)",
            "read pictures of buildings found in the neighbourhood",
            "talk about uses of buildings in the neighbourhood",
            "view video clips of buildings in our neighbourhood",
            "observe charts of buildings at our neighbourhood",
            "draw buildings in the neighbourhood",
            "colour building in the neighbourhood",
            "construct simple structures of buildings found in the school in groups",
            "buy and sell in the shop corner",
            "role play religious leaders in the church, mosque or temple",
            "talk about a visit to hospital in groups.",
            "match and pair items sold in the market",
          ],
          key_inquiry_questions: ["Why do we have buildings in the neighbourhood?"],
        },
        {
          title: "4.3 Plants",
          learning_outcomes: [
            "name parts of plant in the immediate environment",
            "observe plants in the immediate environment",
            "talk about the uses of plants in the immediate environment",
            "care for the plants in the immediate environment",
            "value plants in the immediate environment",
          ],
          suggested_activities: [
            "mention the external parts of a plant(leaves, flower, stem)",
            "identify parts of a plant touch parts of plant",
            "observe different parts of a plant",
            "manipulate different parts of a plant",
            "recite poems about parts of a plant in groups",
            "picture reading on parts of a plant from charts",
            "take nature walk round the school garden",
            "Discuss about the uses of plants",
            "colour drawn pictures parts of a plant",
            "leaf printing",
            "mount flowers on charts in groups",
            "display mounted pictures of parts of a plant on the wall",
            "sort and group flowers of different colours",
            "paste pictures cut outs of parts of a plant",
            "sing songs on parts of plant",
            "watch and listening video clips on parts of plant",
            "water the plants",
            "play games as they mention parts of plant",
          ],
          key_inquiry_questions: ["Why do we have plants?"],
        },
      ],
    },
    {
      title: "5.0 Our School",
      sub_strands: [
        {
          title: "5.1 People in Our School",
          learning_outcomes: [
            "name people working in the school for familiarisation",
            "talk about work done by different people in the school",
            "appreciate the people working in the school for harmonious living",
          ],
          suggested_activities: [
            "mention people found at school, (teachers, security guard, driver, cook)",
            "walk round the school identifying the people by the work they do",
            "mention the work done by people in school",
            "talk about work done by people in school",
            "news tell about work done by people at school in groups",
            "role play work done by people at school",
            "sing songs about work done by people in the school",
            "draw people in school",
            "colour drawn pictures of people working in school",
          ],
          key_inquiry_questions: [
            "Why do we have people in school?",
            "Why do people work in school?",
          ],
        },
        {
          title: "5.2 Things in Our School",
          learning_outcomes: [
            "name things found in school for familiarisation",
            "talk about uses of things found in school",
            "recognise the things found at school",
            "appreciate the things found in school",
          ],
          suggested_activities: [
            "identify things found in school (flag, water tank, play materials, learning materials)",
            "walk round the school identifying the things found in school",
            "mention the things found in school",
            "talk about things found in school",
            "news tell about things found in school",
            "tell the uses of things found in school",
            "use things found in school properly",
            "sing songs about things found at school in groups",
            "draw things found in school",
            "colour a picture of a flag",
            "recite poems on things found in school",
            "model things found in school",
            "match and pair things found in school",
          ],
          key_inquiry_questions: [
            "Why do we have schools?",
            "Why do we have play materials at school?",
          ],
        },
        {
          title: "5.3 Care for School Environment",
          learning_outcomes: [
            "name items used to clean the school environment for health living",
            "identify waste materials and items that require disposal in the school environment",
            "dispose waste materials appropriately from the school environment",
            "embrace living in a clean environment",
          ],
          suggested_activities: [
            "mention items used to clean the school environment",
            "Touch the items used to clean the school environment",
            "talk about the importance of living in a clean environment",
            "identify areas that require cleaning in the school compound",
            "clean different areas in the school compound by picking litter",
            "the litter disposal areas and shown how to dispose litter properly",
            "draw materials used for cleaning the environment",
            "improvise cleaning materials(dust bin, sweeping brooms)",
            "clean working areas after every activity",
            "sing songs as they collect litter",
            "recite poems as they clean working areas",
          ],
          key_inquiry_questions: [
            "Why do we need a clean environment?",
            "How do we clean the school environment?",
          ],
        },
        {
          title: "5.4 Safety in the Environment",
          learning_outcomes: [
            "identify dangerous objects in the school environment",
            "talk about dangerous activities in school",
            "identify strangers in the school environment",
            "tell what to do when dealing with strangers for safety",
            "acknowledge the need for safety in the school environment",
          ],
          suggested_activities: [
            "identify dangerous objects",
            "draw and colour dangerous object",
            "identify dangerous activities",
            "talk about strangers",
            "tell what to do when they meet strangers",
            "handle different materials for safety",
            "clean working areas after an activity",
            "watch videos clips showing dangerous people, places, objects, activities and games",
            "use facilities properly in the school environment",
            "sing songs on identification of dangerous activities in the school environment",
            "recite poems related to safety",
            "dramatise on dealing with strangers",
          ],
          key_inquiry_questions: [
            "Why do you observe safety?",
            "When do you observe safety?",
          ],
        },
        {
            title: "5.5 Weather",
            learning_outcomes: [
                "talk about the different weather conditions",
                "observe weather conditions in the immediate environment",
                "appreciate different weather conditions in the environment",
            ],
            suggested_activities: [
                "talk about weather conditions(cloudy, windy,sunny,rainy)",
                "observe weather chart",
                "identify weather symbols on the weather chart",
                "sing songs about weather conditions",
                "recite poems and rhymes about weather conditions",
                "talk about the activities associated with different weather conditions",
                "Draw different weather conditions",
                "Colour different weather conditions",
                "paint different weather conditions in pairs",
                "Paste weather cut out",
                "watch video clips of different weather conditions",
            ],
            key_inquiry_questions: ["Why do we need rain and sun?"],
        }
      ],
    },
  ],
};

    